#!/usr/bin/env bash

ADDONS_ROOT="app/addons"
LANGS_ROOT="var/langs"

EXCLUDE_REGEX='(^app/lib/|^app/addons/[^/]+/lib/|^var/cache/|^var/files/)'

PHPCS_STANDARD="phpcs.xml.dist"
PHPCS_BIN="${PHPCS_BIN:-phpcs}"

CHECK_HARDCODED_STRINGS="${CHECK_HARDCODED_STRINGS:-1}"

MAX_ADDED_FILE_KB="${MAX_ADDED_FILE_KB:-2048}"
